os: linux
dist: xenial
language: cpp
env:
  global:
    # This flag may limit the parallel build of jobs
    - MAKEFLAGS="-j 4"
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/lcov-1.14
    - ${TRAVIS_BUILD_DIR}/grpc
addons:
  apt:
    update: true
    packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - clang-6.0
      - curl
      - g++
      - make
      - libc++-dev
      - libcurl3-dev
      - libgflags-dev
      - libgtest-dev
      - libtool
      - pkg-config
      - unzip
install:
  # lcov
  - sh ${TRAVIS_BUILD_DIR}/script/install_lcov.sh ${TRAVIS_BUILD_DIR}/
  # gRPC and Protobuf
  - sh ${TRAVIS_BUILD_DIR}/script/clone_grpc.sh ${TRAVIS_BUILD_DIR}/
  # Protobuf
  - sh ${TRAVIS_BUILD_DIR}/script/install_protobuf.sh ${TRAVIS_BUILD_DIR}/
  # gRPC
  - sh ${TRAVIS_BUILD_DIR}/script/install_grpc.sh ${TRAVIS_BUILD_DIR}/

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

compiler:
  - g++

jobs:
  include:
    - stage: build
      script:
        - cd ${TRAVIS_BUILD_DIR}/spec/cpp
        - mkdir build
        - cd build
        - cmake -Dtest=ON ..
        - make

    - stage: test
      script:
        - cd ${TRAVIS_BUILD_DIR}/spec/cpp
          - mkdir build
          - cd build
          - cmake -Dtest=ON ..
          - make
          - GTEST_COLOR=1 ctest --extra-verbose

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
  - coveralls-lcov coverage.info #for open source

notifications:
  email: false
