dist: xenial
language: cpp
#cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/lcov-1.14/
#    - ${TRAVIS_BUILD_DIR}/protobuf/
#    - ${TRAVIS_BUILD_DIR}/grpc/
#    - ${TRAVIS_BUILD_DIR}/libbft/
addons:
  apt:
    update: true
    packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - curl
      - g++
      - make
      - libc++-dev
      - libcurl3-dev
      - libgflags-dev
      - libgtest-dev
      - libtool
      - pkg-config
      - unzip
      - clang-6.0
install:
  # lcov
  - echo "Installing lcov"
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.14.orig.tar.gz
  - tar xf lcov_1.14.orig.tar.gz
  - sudo make -C lcov-1.14/ install
  - gem install coveralls-lcov
  - rm lcov_1.14.orig.tar.gz
  # gRPC and Protobuf
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/grpc/grpc
  - cd grpc
  - git submodule update --init --recursive
  # Protobuf
  - echo "Installing protobuf"
  - cd third_party/protobuf
  - git submodule update --init --recursive
  - sh autogen.sh
  - sh configure --prefix=/usr
  - make
  - sudo make install
  - sudo ldconfig
  # gRPC
  - echo "Installing gRPC"
  - cd ../..
  - make
  - sudo make install

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

compiler:
  - g++

jobs:
  include:
    - stage: build
      script:
        - cd ${TRAVIS_BUILD_DIR}/spec/cpp
        - mkdir build
        - cd build
        - cmake -Dtest=ON ..
        - make
        - GTEST_COLOR=1 ctest --extra-verbose

#    - stage: test
#      script:
#        - cd ${TRAVIS_BUILD_DIR}/spec/cpp/build
#        - ctest --extra-verbose

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
  - coveralls-lcov coverage.info #for open source

notifications:
  email: false
