// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bftp2p.proto
#ifndef GRPC_bftp2p_2eproto__INCLUDED
#define GRPC_bftp2p_2eproto__INCLUDED

#include "bftp2p.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace p2p {

// Defines the service
class P2P final {
 public:
  static constexpr char const* service_full_name() {
    return "p2p.P2P";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Function invoked to send the request
    std::unique_ptr< ::grpc::ClientReaderInterface< ::p2p::Url>> register_me(::grpc::ClientContext* context, const ::p2p::Url& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::p2p::Url>>(register_meRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::p2p::Url>> Asyncregister_me(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::p2p::Url>>(Asyncregister_meRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::p2p::Url>> PrepareAsyncregister_me(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::p2p::Url>>(PrepareAsyncregister_meRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::p2p::Url, ::p2p::Url>> update_services(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::p2p::Url, ::p2p::Url>>(update_servicesRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::p2p::Url, ::p2p::Url>> Asyncupdate_services(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::p2p::Url, ::p2p::Url>>(Asyncupdate_servicesRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::p2p::Url, ::p2p::Url>> PrepareAsyncupdate_services(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::p2p::Url, ::p2p::Url>>(PrepareAsyncupdate_servicesRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Function invoked to send the request
      virtual void register_me(::grpc::ClientContext* context, const ::p2p::Url* request, ::grpc::ClientReadReactor< ::p2p::Url>* reactor) = 0;
      virtual void update_services(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::p2p::Url,::p2p::Url>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::p2p::Url>* register_meRaw(::grpc::ClientContext* context, const ::p2p::Url& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::p2p::Url>* Asyncregister_meRaw(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::p2p::Url>* PrepareAsyncregister_meRaw(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::p2p::Url, ::p2p::Url>* update_servicesRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::p2p::Url, ::p2p::Url>* Asyncupdate_servicesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::p2p::Url, ::p2p::Url>* PrepareAsyncupdate_servicesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::p2p::Url>> register_me(::grpc::ClientContext* context, const ::p2p::Url& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::p2p::Url>>(register_meRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::p2p::Url>> Asyncregister_me(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::p2p::Url>>(Asyncregister_meRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::p2p::Url>> PrepareAsyncregister_me(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::p2p::Url>>(PrepareAsyncregister_meRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::p2p::Url, ::p2p::Url>> update_services(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::p2p::Url, ::p2p::Url>>(update_servicesRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::p2p::Url, ::p2p::Url>> Asyncupdate_services(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::p2p::Url, ::p2p::Url>>(Asyncupdate_servicesRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::p2p::Url, ::p2p::Url>> PrepareAsyncupdate_services(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::p2p::Url, ::p2p::Url>>(PrepareAsyncupdate_servicesRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void register_me(::grpc::ClientContext* context, const ::p2p::Url* request, ::grpc::ClientReadReactor< ::p2p::Url>* reactor) override;
      void update_services(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::p2p::Url,::p2p::Url>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::p2p::Url>* register_meRaw(::grpc::ClientContext* context, const ::p2p::Url& request) override;
    ::grpc::ClientAsyncReader< ::p2p::Url>* Asyncregister_meRaw(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::p2p::Url>* PrepareAsyncregister_meRaw(::grpc::ClientContext* context, const ::p2p::Url& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::p2p::Url, ::p2p::Url>* update_servicesRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::p2p::Url, ::p2p::Url>* Asyncupdate_servicesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::p2p::Url, ::p2p::Url>* PrepareAsyncupdate_servicesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_register_me_;
    const ::grpc::internal::RpcMethod rpcmethod_update_services_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Function invoked to send the request
    virtual ::grpc::Status register_me(::grpc::ServerContext* context, const ::p2p::Url* request, ::grpc::ServerWriter< ::p2p::Url>* writer);
    virtual ::grpc::Status update_services(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::p2p::Url, ::p2p::Url>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_register_me : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_register_me() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_register_me() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_me(::grpc::ServerContext* /*context*/, const ::p2p::Url* /*request*/, ::grpc::ServerWriter< ::p2p::Url>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestregister_me(::grpc::ServerContext* context, ::p2p::Url* request, ::grpc::ServerAsyncWriter< ::p2p::Url>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_update_services : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_update_services() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_update_services() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update_services(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::p2p::Url, ::p2p::Url>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestupdate_services(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::p2p::Url, ::p2p::Url>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_register_me<WithAsyncMethod_update_services<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_register_me : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_register_me() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::p2p::Url, ::p2p::Url>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::p2p::Url* request) { return this->register_me(context, request); }));
    }
    ~WithCallbackMethod_register_me() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_me(::grpc::ServerContext* /*context*/, const ::p2p::Url* /*request*/, ::grpc::ServerWriter< ::p2p::Url>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::p2p::Url>* register_me(
      ::grpc::CallbackServerContext* /*context*/, const ::p2p::Url* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_update_services : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_update_services() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::p2p::Url, ::p2p::Url>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->update_services(context); }));
    }
    ~WithCallbackMethod_update_services() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update_services(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::p2p::Url, ::p2p::Url>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::p2p::Url, ::p2p::Url>* update_services(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_register_me<WithCallbackMethod_update_services<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_register_me : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_register_me() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_register_me() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_me(::grpc::ServerContext* /*context*/, const ::p2p::Url* /*request*/, ::grpc::ServerWriter< ::p2p::Url>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_update_services : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_update_services() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_update_services() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update_services(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::p2p::Url, ::p2p::Url>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_register_me : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_register_me() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_register_me() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_me(::grpc::ServerContext* /*context*/, const ::p2p::Url* /*request*/, ::grpc::ServerWriter< ::p2p::Url>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestregister_me(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_update_services : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_update_services() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_update_services() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update_services(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::p2p::Url, ::p2p::Url>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestupdate_services(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_register_me : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_register_me() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->register_me(context, request); }));
    }
    ~WithRawCallbackMethod_register_me() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_me(::grpc::ServerContext* /*context*/, const ::p2p::Url* /*request*/, ::grpc::ServerWriter< ::p2p::Url>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* register_me(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_update_services : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_update_services() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->update_services(context); }));
    }
    ~WithRawCallbackMethod_update_services() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status update_services(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::p2p::Url, ::p2p::Url>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* update_services(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_register_me : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_register_me() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::p2p::Url, ::p2p::Url>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::p2p::Url, ::p2p::Url>* streamer) {
                       return this->Streamedregister_me(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_register_me() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status register_me(::grpc::ServerContext* /*context*/, const ::p2p::Url* /*request*/, ::grpc::ServerWriter< ::p2p::Url>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedregister_me(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::p2p::Url,::p2p::Url>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_register_me<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_register_me<Service > StreamedService;
};

}  // namespace p2p


#endif  // GRPC_bftp2p_2eproto__INCLUDED
