// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bftevent.proto

#include "bftevent.pb.h"
#include "bftevent.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace bftevent {

static const char* BFTEvent_method_names[] = {
  "/bftevent.BFTEvent/informEvent",
};

std::unique_ptr< BFTEvent::Stub> BFTEvent::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BFTEvent::Stub> stub(new BFTEvent::Stub(channel, options));
  return stub;
}

BFTEvent::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_informEvent_(BFTEvent_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BFTEvent::Stub::informEvent(::grpc::ClientContext* context, const ::bftevent::EventInform& request, ::bftevent::EventReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bftevent::EventInform, ::bftevent::EventReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_informEvent_, context, request, response);
}

void BFTEvent::Stub::async::informEvent(::grpc::ClientContext* context, const ::bftevent::EventInform* request, ::bftevent::EventReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bftevent::EventInform, ::bftevent::EventReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_informEvent_, context, request, response, std::move(f));
}

void BFTEvent::Stub::async::informEvent(::grpc::ClientContext* context, const ::bftevent::EventInform* request, ::bftevent::EventReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_informEvent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bftevent::EventReply>* BFTEvent::Stub::PrepareAsyncinformEventRaw(::grpc::ClientContext* context, const ::bftevent::EventInform& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bftevent::EventReply, ::bftevent::EventInform, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_informEvent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bftevent::EventReply>* BFTEvent::Stub::AsyncinformEventRaw(::grpc::ClientContext* context, const ::bftevent::EventInform& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncinformEventRaw(context, request, cq);
  result->StartCall();
  return result;
}

BFTEvent::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BFTEvent_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BFTEvent::Service, ::bftevent::EventInform, ::bftevent::EventReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BFTEvent::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bftevent::EventInform* req,
             ::bftevent::EventReply* resp) {
               return service->informEvent(ctx, req, resp);
             }, this)));
}

BFTEvent::Service::~Service() {
}

::grpc::Status BFTEvent::Service::informEvent(::grpc::ServerContext* context, const ::bftevent::EventInform* request, ::bftevent::EventReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bftevent

