// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bftevent.proto

#include "bftevent.pb.h"
#include "bftevent.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace bftevent {

static const char* BFTEvent_method_names[] = {
  "/bftevent.BFTEvent/informEvent",
};

std::unique_ptr< BFTEvent::Stub> BFTEvent::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BFTEvent::Stub> stub(new BFTEvent::Stub(channel));
  return stub;
}

BFTEvent::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_informEvent_(BFTEvent_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BFTEvent::Stub::informEvent(::grpc::ClientContext* context, const ::bftevent::EventInform& request, ::bftevent::EventReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_informEvent_, context, request, response);
}

void BFTEvent::Stub::experimental_async::informEvent(::grpc::ClientContext* context, const ::bftevent::EventInform* request, ::bftevent::EventReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_informEvent_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::bftevent::EventReply>* BFTEvent::Stub::AsyncinformEventRaw(::grpc::ClientContext* context, const ::bftevent::EventInform& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bftevent::EventReply>::Create(channel_.get(), cq, rpcmethod_informEvent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::bftevent::EventReply>* BFTEvent::Stub::PrepareAsyncinformEventRaw(::grpc::ClientContext* context, const ::bftevent::EventInform& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bftevent::EventReply>::Create(channel_.get(), cq, rpcmethod_informEvent_, context, request, false);
}

BFTEvent::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BFTEvent_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BFTEvent::Service, ::bftevent::EventInform, ::bftevent::EventReply>(
          std::mem_fn(&BFTEvent::Service::informEvent), this)));
}

BFTEvent::Service::~Service() {
}

::grpc::Status BFTEvent::Service::informEvent(::grpc::ServerContext* context, const ::bftevent::EventInform* request, ::bftevent::EventReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bftevent

