##### Protobuf Rules for Bazel
##### See https://github.com/bazelbuild/rules_proto
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

##### gRPC Rules for Bazel
##### See https://github.com/grpc/grpc/blob/master/src/cpp/README.md#make

# https://github.com/grpc/grpc/commit/de893acb6aef88484a427e64b96727e4926fdcfd
# v1.51.1 0a82c02a9b817a53574994374dcff53f2e961df2
# Requires >= c++14 (in this case, c++17). Please check .bazelrc file.

http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/0a82c02a9b817a53574994374dcff53f2e961df2.tar.gz",
    ],
    sha256 = "92fdb11e9bdc770e16caedf9c13d1688ce476a0c763c11d3871781af3881ac28",
    strip_prefix = "grpc-0a82c02a9b817a53574994374dcff53f2e961df2",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()


# CLANG-TIDY-INTEGRATION (experimental) - https://github.com/erenon/bazel_clang_tidy

http_archive(
    name = "bazel_clang_tidy",
    sha256 = "2c2d7e290d78c0020c60f07cec6e3820cce64c285153de8e96637027ee5e3b8e",
    strip_prefix = "bazel_clang_tidy-31d62bf825a94468b3d35c5ffd4e014e1c0ff566",
    url = "https://github.com/erenon/bazel_clang_tidy/archive/31d62bf825a94468b3d35c5ffd4e014e1c0ff566.tar.gz",
)
# BUILD WITH clang-tidy: bazel build //... --config clang-tidy

#####################################################
# tooling for vscode (generate compile_commands.json)
#####################################################

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
http_archive(
    name = "hedron_compile_commands",
    sha256 = "7a42f4a4a75a22476eb5eb0bc8fa0294034f238f007f11b7befb8f05ced1f552",
    # Replace the commit hash in both places (below) with the latest, rather than using the stale one here.
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
    url = "https://github.com/hedronvision/bazel-compile-commands-extractor/archive/a69b071b78120a6cdadc9f6a9968ed36c2206556.tar.gz",
    strip_prefix = "bazel-compile-commands-extractor-a69b071b78120a6cdadc9f6a9968ed36c2206556",
    # When you first run this tool, it'll recommend a sha256 hash to put here with a message like: "DEBUG: Rule 'hedron_compile_commands' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = ..."
)
load("@hedron_compile_commands//:workspace_setup.bzl", "hedron_compile_commands_setup")
hedron_compile_commands_setup()
# RUN: bazel run @hedron_compile_commands//:refresh_all


